name: Bug Report
description: Create a report to help us improve
body:
  - type: markdown
    attributes:
      value: Thanks for taking time to fill out this bug report!
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Provide which product the issue is related to.
      options:
        - dotnet CLI (dotnet new)
        - Visual Studio
        - dotnet CLI & Visual Studio
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe The Bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        Steps:
        1. 
        2. 
        3. 
    validations:
      required: true
  - type: textarea
    id: dotnet-version
    attributes:
      label: dotnet Info
      description: Provide the output of **`dotnet --info`** to understand what the dotnet version is.
    validations:
      required: true
  - type: input
    id: VS-version
    attributes:
      label: Visual Studio Version
      description: In case the issue is also reproduced in Visual Studio, please additionally specify Visual Studio version.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide any details that could help with the investigation.