name: Create PR on Template JSON Changes

on:
  push:
    branches:
      - main
    paths:
      - 'src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Schemas/JSON/template.json'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          repository: dotnet/templating
          ref: main
          path: source

      - name: Checkout Target
        uses: actions/checkout@v2
        with:
          repository: SchemaStore/schemastore
          ref: master
          path: target

      - name: Copy Template JSON
        run: |
          cp source/src/Microsoft.TemplateEngine.Orchestrator.RunnableProjects/Schemas/JSON/template.json target/src/schemas/json/template.json

      - name: Commit Changes
        run: |
          cd target
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Sync changes with template.json"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          commit-message: "Sync changes to template.json"
          branch: "sync/template-json"
          title: "Sync changes to template.json from dotnet/templating"
          body: |
            This pull request was automatically created to sync the changes to `template.json` from the `dotnet/templating` repository to the `schemastore` repository.

            **Changes**
            ```
            ${{ github.event.head_commit.modified | join('\n') }}
            ```
          base: "master"
          labels: "auto-generated"
